### ISSUE TITLE
Add "ÁKK" as an acceptable VAT key ("áfakulcs")

### ISSUE THREAD

**Issue by balazsnemeth** [ewngs/szamlazz.js#14]
```
      if (['TAM', 'AAM', 'EU', 'EUK', 'MAA''].includes(this._options.vat)) {
```

should be 
```
      if (['TAM', 'AAM', 'EU', 'EUK', 'MAA', 'ÁKK'].includes(this._options.vat)) {
```

Because "ÁKK" key is also acceptable and works well.

**Comment by mondalaci** [comment]
Resolved by #15. Please [close issues using keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) in upcoming PRs.
