### ISSUE TITLE
Error: A számla kibocsátásához szükség van a vevő adószámára.

### ISSUE THREAD

**Issue by LaKing** [ewngs/szamlazz.js#16]
According to [szamlazz.hu](https://www.szamlazz.hu/szamla/tudastar/funkcionalitas/vevo_adoszama_a_szamlan) we need the "adoalany" field transmitted.

```<element name="adoalany" type="int" maxOccurs="1" minOccurs="0"></element>            <!-- Possible values for the "type" field: 7:business is based outside of the European Union, 6:business is based in the Europen Union, 1: has a hungarian tax number, 0: we don't know, if the buyer has a tax number, -1: no tax number -->```

X | típus
-- | --
7 | EU-n kívüli vállalkozás
6 | EU-s vállalkozás
1 | van magyar adószáma
0​ | nem tudjuk hogy a vásárló adóalany-e
-1 | nincs adószáma (azaz nincs magyar adószáma)

**Comment by mondalaci** [comment]
Thanks for the heads-up, and feel free to send a PR.

**Comment by necccc** [comment]
This PR resolves this https://github.com/ewngs/szamlazz.js/pull/17
