### ISSUE TITLE
Unable to install szamlazz

### ISSUE THREAD

**Issue by cheetahtariq** [ewngs/szamlazz.js#26]
command " npm install szamlazz.js --save " is not working.
error - " deprecated libxmljs2@0.21.6: Please use >=0.25.4 "

![image](https://user-images.githubusercontent.com/61146357/150385309-36fa4af7-6645-463f-a5db-71326525ae62.png)

**Comment by Tibi02** [comment]
@cheetahtariq - This happens because there is no pre-built binary of libxmljs2 available for your node version (v16).
It should work fine with node 12 or 14.

**Comment by mondalaci** [comment]
I cannot reproduce this issue with node 16.13.0. Feel free to retry.
