### ISSUE TITLE
Seller's `defaultOptions` gets overwritten by `merge.recursive`

### ISSUE THREAD

**Issue by geiszla** [ewngs/szamlazz.js#55]
Since the `merge.recursive` call inside the `Seller` class does not have the `clone` option, it will not clone the input object, therefore every call of the `Seller` constructor will overwrite the `defaultOptions` with the user's options.

This also means that seller details can mix (e.g., bank account of a seller can appear on another invoice).

**Comment by ert78gb** [comment]
thx for reporting. I will fix it today
