### ISSUE TITLE
Feature Request: Add Cash On Delivery (COD) Payment Method

### ISSUE THREAD

**Issue by dev-el-op** [ewngs/szamlazz.js#63]
Hello,

 I am currently utilizing your code in my project. I am writing to suggest a potential enhancement that could broaden the utility of your billing system. In my use case, and possibly for other users as well, there's a need for a Cash On Delivery (COD) payment option. This feature would be incredibly beneficial for businesses that deal with direct customer deliveries where online transactions might not always be feasible.

**Comment by ert78gb** [comment]
PR is more than welcome. Please don't forget the test :)

**Comment by ert78gb** [comment]
Based on the [szamlazz.hu documentation](https://tudastar.szamlazz.hu/gyik/milyen-fizetesi-modokat-hasznalhatok) the `PaymentMethod` is an extendable field. 

When you create an new invoice just create a new `PaymentMethod` like

```javascript
const invoice = new Invoice({
  ...
  paymentMethod: new PaymentMethod('my method', 'comment of my method'),
  ...
})
```
