### ISSUE TITLE
Would it be possbile to integrate more PaymentMethods?

### ISSUE THREAD

**Issue by villszer** [ewngs/szamlazz.js#69]
My users are paying with [Barion](https://www.barion.com/hu/) but there is no option in the `PaymentMethod` for that.

**Comment by ert78gb** [comment]
Based on the [szamlazz.hu documentation](https://tudastar.szamlazz.hu/gyik/milyen-fizetesi-modokat-hasznalhatok) the `PaymentMethod` is an extendable field. 

When you create an new invoice just create a new `PaymentMethod` like

```javascript
const invoice = new Invoice({
  ...
  paymentMethod: new PaymentMethod('my method', 'comment of my method'),
  ...
})
```

**Comment by villszer** [comment]
Wow, thank you very much, that sounds really good! Will try it.
