### ISSUE TITLE
Adding customerAccount field to invoice response

### ISSUE THREAD

**Issue by laszloerno** [ewngs/szamlazz.js#71]
Hi

we generate nearly 500-700 invoices per monnth our customers lose the mails or dont't find it anymore. 
So we would store the value and implement in our customer profile a possibility to navigate to this link.

to be changed/added line in Client.js:114
      customerAccount: httpResponse.headers.szlahu_vevoifiokurl,

can this be added?
thanks

**Comment by ert78gb** [comment]
Sure, please open the PR. thx
